import { ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { theme } from "../../src/theme";
const days = [35, 62, 44, 86, 58, 76, 92];
export default function ProgressScreen() {
  return <SafeAreaView style={styles.safe} edges={["top"]}><ScrollView contentContainerStyle={styles.content}>
    <Text style={styles.eyebrow}>НЕ ПРОСТО АКТИВНОСТЬ</Text><Text style={styles.title}>Прогресс</Text>
    <View style={styles.stats}><View style={styles.stat}><Text style={styles.statValue}>240</Text><Text style={styles.statLabel}>XP за неделю</Text></View><View style={styles.stat}><Text style={styles.statValue}>6</Text><Text style={styles.statLabel}>завершено</Text></View><View style={styles.stat}><Text style={styles.statValue}>3</Text><Text style={styles.statLabel}>навыка растут</Text></View></View>
    <View style={styles.card}><Text style={styles.cardTitle}>Ритм недели</Text><Text style={styles.cardSubtitle}>XP показывает действия. Мастерство меняется только после обзора.</Text><View style={styles.chart}>{days.map((value, index) => <View key={index} style={styles.barColumn}><View style={[styles.bar, { height: value }]} /><Text style={styles.day}>{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"][index]}</Text></View>)}</View></View>
    <View style={styles.callout}><Text style={styles.calloutTitle}>Честная картина</Text><Text style={styles.calloutText}>Ты много работал над фундаментом, но навык «Markdown и второй мозг» уже просит повторения.</Text></View>
  </ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: theme.colors.canvas }, content: { padding: 20, paddingBottom: 40, gap: 18 }, eyebrow: { color: theme.colors.green, fontSize: 12, fontWeight: "800", letterSpacing: 1 }, title: { color: theme.colors.text, fontSize: 34, fontWeight: "700", marginTop: -10 }, stats: { flexDirection: "row", gap: 10 }, stat: { flex: 1, backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 14, padding: 14 }, statValue: { color: theme.colors.text, fontSize: 24, fontWeight: "800" }, statLabel: { color: theme.colors.muted, fontSize: 12, marginTop: 3 }, card: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 18, padding: 18 }, cardTitle: { color: theme.colors.text, fontSize: 20, fontWeight: "700" }, cardSubtitle: { color: theme.colors.muted, lineHeight: 20, marginTop: 6 }, chart: { height: 135, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginTop: 22 }, barColumn: { alignItems: "center", gap: 8, width: 30 }, bar: { width: 18, backgroundColor: theme.colors.blue, borderRadius: 5 }, day: { color: theme.colors.muted, fontSize: 11 }, callout: { backgroundColor: theme.colors.orangeSoft, borderRadius: 16, padding: 18 }, calloutTitle: { color: theme.colors.text, fontSize: 17, fontWeight: "700" }, calloutText: { color: theme.colors.muted, lineHeight: 22, marginTop: 6 } });
