import { completeQuest } from "./progress";
import { repetitionStatus, scheduleSkillAfterReview, tomorrowFrom } from "./repetition";
import type { PersonalRepository } from "./repository";
import { wouldCreateSkillCycle } from "./skillGraph";
import type { Goal, GoalStatus, Profile, Quest, Skill, SkillEdge, SupportLevel, WeeklyReview } from "./types";
export interface PersonalServiceOptions { now?: () => string; createId?: (prefix: string) => string; }
export class PersonalService {
  private readonly now: () => string; private readonly createId: (prefix: string) => string;
  constructor(private readonly repository: PersonalRepository, options: PersonalServiceOptions = {}) { this.now = options.now ?? (() => new Date().toISOString()); this.createId = options.createId ?? ((prefix) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`); }
  async createGoal(input: { profileId: string; displayName: string; title: string; description?: string }): Promise<Goal> { const title = requiredTitle(input.title, "Goal title"); const timestamp = this.now(); const profile: Profile = { id: input.profileId, displayName: requiredTitle(input.displayName, "Display name"), createdAt: timestamp, updatedAt: timestamp }; await this.repository.ensureProfile(profile); const goal: Goal = { id: this.createId("goal"), profileId: input.profileId, title, description: cleanOptional(input.description), status: "active", createdAt: timestamp, updatedAt: timestamp }; await this.repository.saveGoal(goal); return goal; }
  async setGoalStatus(goalId: string, status: GoalStatus): Promise<Goal> { const goal = await this.requireGoal(goalId); const updated = { ...goal, status, updatedAt: this.now() }; await this.repository.saveGoal(updated); return updated; }
  async createSkill(input: { goalId: string; title: string; description?: string; supportLevel: SupportLevel }): Promise<Skill> { const goal = await this.requireGoal(input.goalId); if (goal.status === "archived") throw new Error("Cannot add a skill to an archived goal"); const timestamp = this.now(); const skill: Skill = { id: this.createId("skill"), goalId: input.goalId, title: requiredTitle(input.title, "Skill title"), description: cleanOptional(input.description), supportLevel: input.supportLevel, status: "growing", masteryScore: 0, createdAt: timestamp, updatedAt: timestamp }; await this.repository.saveSkill(skill); return skill; }
  async reviewSkill(input: { skillId: string; masteryScore: number; supportLevel: SupportLevel; note: string }): Promise<Skill> { const skill = await this.requireSkill(input.skillId); if (!Number.isInteger(input.masteryScore) || input.masteryScore < 0 || input.masteryScore > 100) throw new Error("Mastery score must be an integer from 0 to 100"); if (![0, 1, 2, 3].includes(input.supportLevel)) throw new Error("Support level must be from 0 to 3"); const note = requiredNote(input.note); if (skill.masteryScore === input.masteryScore && skill.supportLevel === input.supportLevel) throw new Error("Review must change mastery or support"); const timestamp = this.now(); const reviewed = scheduleSkillAfterReview({ ...skill, masteryScore: input.masteryScore, supportLevel: input.supportLevel, updatedAt: timestamp }, timestamp); const event = { id: this.createId("event"), type: "skill_reviewed" as const, entityId: skill.id, occurredAt: timestamp, xpDelta: 0, metadata: { previousMastery: skill.masteryScore, masteryScore: reviewed.masteryScore, previousSupport: skill.supportLevel, supportLevel: reviewed.supportLevel, nextReviewAt: reviewed.nextReviewAt ?? "", note } }; await this.repository.saveReviewedSkillWithEvent(reviewed, event); return reviewed; }
  async pauseSkill(skillId: string): Promise<Skill> { const skill = await this.requireSkill(skillId); if (skill.status === "paused") return skill; const timestamp = this.now(); const updated: Skill = { ...skill, status: "paused", nextReviewAt: undefined, updatedAt: timestamp }; const event = { id: this.createId("event"), type: "skill_level_changed" as const, entityId: skill.id, occurredAt: timestamp, xpDelta: 0, metadata: { reason: "paused_without_penalty", previousStatus: skill.status, status: updated.status } }; await this.repository.saveReviewedSkillWithEvent(updated, event); return updated; }
  async recoverSkill(skillId: string): Promise<Skill> { const skill = await this.requireSkill(skillId); const timestamp = this.now(); const currentStatus = repetitionStatus(skill, timestamp); if (currentStatus !== "due" && currentStatus !== "fading" && currentStatus !== "paused") throw new Error("Skill is not waiting for recovery"); const updated: Skill = { ...skill, status: "growing", supportLevel: Math.min(3, skill.supportLevel + 1) as SupportLevel, nextReviewAt: tomorrowFrom(timestamp), updatedAt: timestamp }; const event = { id: this.createId("event"), type: "skill_level_changed" as const, entityId: skill.id, occurredAt: timestamp, xpDelta: 0, metadata: { reason: "gentle_recovery", previousStatus: currentStatus, status: updated.status, previousSupport: skill.supportLevel, supportLevel: updated.supportLevel } }; await this.repository.saveReviewedSkillWithEvent(updated, event); return updated; }
  async connectSkills(input: { parentSkillId: string; childSkillId: string }): Promise<SkillEdge> { if (input.parentSkillId === input.childSkillId) throw new Error("A skill cannot depend on itself"); const [parent, child] = await Promise.all([this.requireSkill(input.parentSkillId), this.requireSkill(input.childSkillId)]); if (parent.goalId !== child.goalId) throw new Error("Connected skills must belong to the same goal"); const edges = await this.repository.listSkillEdges(); const existing = edges.find((edge) => edge.parentSkillId === parent.id && edge.childSkillId === child.id); if (existing) return existing; if (wouldCreateSkillCycle(edges, parent.id, child.id)) throw new Error("Skill relationship would create a cycle"); const edge: SkillEdge = { id: this.createId("skill_edge"), parentSkillId: parent.id, childSkillId: child.id }; await this.repository.saveSkillEdge(edge); return edge; }
  async disconnectSkills(input: { parentSkillId: string; childSkillId: string }) { const edge = (await this.repository.listSkillEdges()).find((candidate) => candidate.parentSkillId === input.parentSkillId && candidate.childSkillId === input.childSkillId); if (!edge) return false; await this.repository.deleteSkillEdge(edge.id); return true; }
  async createQuest(input: { title: string; description?: string; skillIds: string[]; supportLevel: SupportLevel; xpReward?: number; scheduledFor?: string }): Promise<Quest> { const skillIds = [...new Set(input.skillIds)]; if (skillIds.length === 0) throw new Error("A quest must be connected to at least one skill"); for (const skillId of skillIds) if (!(await this.repository.getSkill(skillId))) throw new Error(`Skill not found: ${skillId}`); const xpReward = input.xpReward ?? 10; if (!Number.isInteger(xpReward) || xpReward < 0) throw new Error("XP reward must be a non-negative integer"); const timestamp = this.now(); const quest: Quest = { id: this.createId("quest"), title: requiredTitle(input.title, "Quest title"), description: cleanOptional(input.description), supportLevel: input.supportLevel, status: "active", xpReward, scheduledFor: cleanOptional(input.scheduledFor), createdAt: timestamp, updatedAt: timestamp }; await this.repository.saveQuest(quest, skillIds.map((skillId) => ({ questId: quest.id, skillId, contributionWeight: 1 }))); return quest; }
  async finishQuest(input: { questId: string; evidenceNote?: string; evidenceUrl?: string; reflection?: string }) { const quest = await this.repository.getQuest(input.questId); if (!quest) throw new Error(`Quest not found: ${input.questId}`); const timestamp = this.now(); const result = completeQuest({ id: this.createId("completion"), quest, completedAt: timestamp, evidenceNote: input.evidenceNote, evidenceUrl: input.evidenceUrl, reflection: input.reflection }); await this.repository.saveCompletionWithEvent(result.completion, result.event, { ...quest, status: "completed", updatedAt: timestamp }); return result; }
  async completeWeeklyReview(input: { profileId: string; displayName: string; achievements?: string; blockers?: string; decisions: string }): Promise<WeeklyReview> { const timestamp = this.now(); await this.repository.ensureProfile({ id: input.profileId, displayName: requiredTitle(input.displayName, "Display name"), createdAt: timestamp, updatedAt: timestamp }); const weekStart = startOfWeek(timestamp); const existing = await this.repository.getWeeklyReviewByWeek(input.profileId, weekStart); const review: WeeklyReview = { id: existing?.id ?? this.createId("review"), profileId: input.profileId, weekStart, achievements: cleanOptional(input.achievements), blockers: cleanOptional(input.blockers), decisions: requiredTitle(input.decisions, "Next-week decision"), completedAt: timestamp }; const event = { id: this.createId("event"), type: "weekly_review_completed" as const, entityId: review.id, occurredAt: timestamp, xpDelta: 0, metadata: { hasAchievements: Boolean(review.achievements), hasBlockers: Boolean(review.blockers) } }; await this.repository.saveWeeklyReviewWithEvent(review, event); return review; }
  private async requireGoal(goalId: string) { const goal = await this.repository.getGoal(goalId); if (!goal) throw new Error(`Goal not found: ${goalId}`); return goal; } private async requireSkill(skillId: string) { const skill = await this.repository.getSkill(skillId); if (!skill) throw new Error(`Skill not found: ${skillId}`); return skill; }
}
function requiredTitle(value: string, label: string) { const cleaned = value.trim(); if (!cleaned) throw new Error(`${label} is required`); if (cleaned.length > 120) throw new Error(`${label} must be 120 characters or fewer`); return cleaned; } function requiredNote(value: string) { const cleaned = value.trim(); if (!cleaned) throw new Error("Review note is required"); if (cleaned.length > 500) throw new Error("Review note must be 500 characters or fewer"); return cleaned; } function cleanOptional(value?: string) { const cleaned = value?.trim(); return cleaned || undefined; } function startOfWeek(value: string) { const date = new Date(value); const day = (date.getDay() + 6) % 7; date.setDate(date.getDate() - day); const pad = (part: number) => String(part).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}`; }
