import { useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { usePersonalApp } from "../application/PersonalAppProvider";
import { createExternalNoteLink, externalNoteDisplayValue, externalNoteOpenUrl } from "../domain/externalNotes";
import type { ExternalNoteEntityType, ExternalNoteLink } from "../domain/types";
import { theme } from "../theme";

export function ExternalNoteCard({ entityType, entityId }: { entityType: ExternalNoteEntityType; entityId: string }) {
  const { repository } = usePersonalApp(); const [link, setLink] = useState<ExternalNoteLink | null>(null); const [input, setInput] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; repository.getExternalNoteLink(entityType, entityId).then((value) => { if (active) { setLink(value); setInput(externalNoteDisplayValue(value)); } }); return () => { active = false; }; }, [entityId, entityType, repository]);
  async function save() { if (!input.trim() || saving) return; setSaving(true); setMessage(""); try { const next = createExternalNoteLink(entityType, entityId, input, new Date().toISOString()); await repository.saveExternalNoteLink(next); setLink(next); setInput(externalNoteDisplayValue(next)); setMessage("Ссылка сохранена локально."); } catch (error) { setMessage(error instanceof Error ? error.message : "Не удалось сохранить ссылку"); } finally { setSaving(false); } }
  async function open() { if (!link) return; setMessage(""); try { await Linking.openURL(externalNoteOpenUrl(link)); } catch { setMessage(link.provider === "obsidian" ? "Не удалось открыть Obsidian. Проверь приложение и путь к заметке." : "Не удалось открыть ссылку."); } }
  async function remove() { if (!link || saving) return; setSaving(true); try { await repository.deleteExternalNoteLink(entityType, entityId); setLink(null); setInput(""); setMessage("Ссылка удалена. Сама заметка не затронута."); } finally { setSaving(false); } }
  return <View style={styles.card}><Text style={styles.title}>Внешняя заметка</Text><Text style={styles.text}>Путь внутри Obsidian vault, `obsidian://` URI или https-ссылка. Levera хранит только связь.</Text><TextInput value={input} onChangeText={setInput} autoCapitalize="none" autoCorrect={false} placeholder="Levera/Skills/My skill.md" placeholderTextColor={theme.colors.muted} style={styles.input} />
    <View style={styles.actions}><Pressable disabled={!input.trim() || saving} onPress={save} style={[styles.save, (!input.trim() || saving) && styles.disabled]}>{saving ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.saveText}>{link ? "Обновить" : "Связать"}</Text>}</Pressable>{link ? <Pressable disabled={saving} onPress={open} style={styles.open}><Text style={styles.openText}>Открыть</Text></Pressable> : null}</View>
    {link ? <Pressable disabled={saving} onPress={remove}><Text style={styles.remove}>Удалить только связь</Text></Pressable> : null}{message ? <Text style={styles.message}>{message}</Text> : null}
  </View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: theme.colors.surface, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 16, padding: 18, marginTop: 12 }, title: { color: theme.colors.text, fontSize: 19, fontWeight: "800" }, text: { color: theme.colors.muted, lineHeight: 20, marginTop: 5 }, input: { minHeight: 48, color: theme.colors.text, backgroundColor: theme.colors.canvas, borderWidth: 1, borderColor: theme.colors.border, borderRadius: 11, paddingHorizontal: 12, marginTop: 14 }, actions: { flexDirection: "row", gap: 9, marginTop: 9 }, save: { flex: 1, minHeight: 46, backgroundColor: theme.colors.blue, borderRadius: 10, alignItems: "center", justifyContent: "center" }, saveText: { color: "#FFFFFF", fontWeight: "800" }, open: { flex: 1, minHeight: 46, borderWidth: 1, borderColor: theme.colors.blue, borderRadius: 10, alignItems: "center", justifyContent: "center" }, openText: { color: theme.colors.blue, fontWeight: "800" }, disabled: { opacity: 0.45 }, remove: { color: theme.colors.red, fontWeight: "700", textAlign: "center", paddingTop: 13 }, message: { color: theme.colors.muted, lineHeight: 19, marginTop: 9 } });
