import type { CompletedQuestSummary, PersonalRepository } from "../domain/repository";
import type { Goal, Profile, ProgressEvent, Quest, QuestCompletion, QuestSkill, Skill, SkillEdge, WeeklyReview } from "../domain/types";
export class MemoryPersonalRepository implements PersonalRepository {
  readonly profiles = new Map<string, Profile>(); readonly goals = new Map<string, Goal>(); readonly skills = new Map<string, Skill>(); readonly skillEdges = new Map<string, SkillEdge>(); readonly quests = new Map<string, Quest>(); readonly questLinks: QuestSkill[] = []; readonly completions: QuestCompletion[] = []; readonly events: ProgressEvent[] = []; readonly weeklyReviews: WeeklyReview[] = [];
  async ensureProfile(profile: Profile) { this.profiles.set(profile.id, this.profiles.get(profile.id) ?? profile); }
  async getGoal(id: string) { return this.goals.get(id) ?? null; } async saveGoal(goal: Goal) { this.goals.set(goal.id, goal); } async listGoals(profileId: string) { return [...this.goals.values()].filter((goal) => goal.profileId === profileId); }
  async getSkill(id: string) { return this.skills.get(id) ?? null; } async saveSkill(skill: Skill) { this.skills.set(skill.id, skill); } async saveReviewedSkillWithEvent(skill: Skill, event: ProgressEvent) { this.skills.set(skill.id, skill); this.events.push(event); } async listSkills(goalId: string) { return [...this.skills.values()].filter((skill) => skill.goalId === goalId); }
  async listSkillsForProfile(profileId: string) { const goalIds = new Set([...this.goals.values()].filter((goal) => goal.profileId === profileId && goal.status !== "archived").map((goal) => goal.id)); return [...this.skills.values()].filter((skill) => goalIds.has(skill.goalId)); }
  async saveSkillEdge(edge: SkillEdge) { this.skillEdges.set(edge.id, edge); } async deleteSkillEdge(id: string) { this.skillEdges.delete(id); } async listSkillEdges() { return [...this.skillEdges.values()]; }
  async getQuest(id: string) { return this.quests.get(id) ?? null; } async saveQuest(quest: Quest, links: QuestSkill[]) { this.quests.set(quest.id, quest); this.questLinks.splice(0, this.questLinks.length, ...this.questLinks.filter((link) => link.questId !== quest.id), ...links); } async listQuests() { return [...this.quests.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); } async listQuestSkills(questId: string) { return this.questLinks.filter((link) => link.questId === questId); } async listActiveQuests() { return [...this.quests.values()].filter((quest) => quest.status === "active"); }
  async saveCompletionWithEvent(completion: QuestCompletion, event: ProgressEvent, completedQuest: Quest) { this.completions.push(completion); this.events.push(event); this.quests.set(completedQuest.id, completedQuest); } async listCompletions(questId: string) { return this.completions.filter((completion) => completion.questId === questId); } async listCompletedQuests(limit = 50) { return this.buildHistory().slice(0, limit); } async listSkillHistory(skillId: string, limit = 50) { return this.buildHistory().filter((item) => item.skillIds.includes(skillId)).slice(0, limit); }
  async saveWeeklyReviewWithEvent(review: WeeklyReview, event: ProgressEvent) { this.weeklyReviews.push(review); this.events.push(event); } async listWeeklyReviews(profileId: string, limit = 12) { return this.weeklyReviews.filter((review) => review.profileId === profileId).sort((a, b) => b.completedAt.localeCompare(a.completedAt)).slice(0, limit); } async listProgressEvents(entityId: string) { return this.events.filter((event) => event.entityId === entityId); }
  private buildHistory(): CompletedQuestSummary[] { return [...this.completions].sort((a, b) => b.completedAt.localeCompare(a.completedAt)).map((completion) => { const quest = this.quests.get(completion.questId); if (!quest) throw new Error(`Quest not found for completion: ${completion.questId}`); return { questId: quest.id, title: quest.title, completedAt: completion.completedAt, xpGranted: completion.xpGranted, evidenceNote: completion.evidenceNote, reflection: completion.reflection, skillIds: this.questLinks.filter((link) => link.questId === quest.id).map((link) => link.skillId) }; }); }
}
